CFLAGS = -Wall -Werror
dep : serveur client usage
all : clean dep
clean : 
	-rm server client
usage:
	@echo ""
	@echo "Usage :"
	@echo "    On the server computer, start the server:"
	@echo "       ./server port"
	@echo "    On the client computer, start the client:"
	@echo "       ./client ipserver portserver"
	@echo ""
	
